#+TITLE: Experimental init.el
#+PROPERTY: tangle "~/.emacs.d/experminal-init.el"
#+STARTUP: content

* 参考
- [[https://ayatakesi.github.io/emacs/29.4/html/index.html][Emacs Japanese]]
- https://takaxp.github.io/org-ja.html
- [[https://www.gnu.org/software/emacs/manual/html_node/eintr/][An Introduction to Programing in Emacs Lisp]]
- [[https://www.google.com/]]
- file:///usr/local/share/GNUstep/Documentation/Developer/Base/ProgrammingManual/gs-base/index.html
- file:///usr/local/share/GNUstep/Documentation/Developer/Base/Reference/Base.html

* このファイルの使用方法
#+BEGIN_SRC shell :tangle no
  alias emacs2='emacs -Q -l ~/.emacs.d/experminal-init.el'
  # then use: emacs2 <Enter>
#+END_SRC

* ファイルの生成方法
#+BEGIN_SRC :tangle no
C-c C-v C-t
#+END_SRC

* Script Runner

これはブラウザの拡張機能であり、以下のソースを GNU Manuals というタイトルのもとに貼り付けて利用すれば、おかしな翻訳を避けることができる。
** TODO あれ、javascript で C-M-\ =indent-region= すると、4space のインデントになってしまう。どこかで見直そう。

#+begin_src javascript
  const classes = [
      "example",
      "category-def",
      "def-name",
      "def-var-arguments"
  ]

  const qclasses = classes.map((v) => "." + v).join(",")

  document.querySelectorAll(qclasses).forEach((el) => {
      if (!el.hasAttribute("translate")) {
          el.setAttribute("translate", "no");
      }
  });
#+end_src

* スタートアップメッセージ
#+BEGIN_SRC elisp :tangle yes
  ;;; Code:

  (with-current-buffer "*scratch*"
    (insert ";;; loading Experimental init.el\n")
    (insert ";;; Emacs " emacs-version "\n")
    (insert "\n")
    (insert "\n"))

  (when (file-directory-p "~/.emacs.d/lisp")
    (push (expand-file-name "~/.emacs.d/lisp") load-path))

  (setq gc-cons-threshold 100000000)
  (setq read-process-output-max (* 80 1024 1024)) ;; 8mb
  ;; カスタムコマンドのロード
  (require 'kf-command)
  (require 'mpascal)

  (add-to-list 'auto-mode-alist
               '("\\.\\(p\\|pas\\|dpr\\|dpk\\)\\'" . mpascal-mode))
#+END_SRC
* 基本設定
#+begin_src elisp :tangle yes
  (setq inhibit-startup-message t)

  (scroll-bar-mode -1)        ; Disable visible scrollbar
  (tool-bar-mode -1)          ; Disable the toolbar
  (tooltip-mode -1)           ; Disable tooltips
  (set-fringe-mode 10)        ; Give some breathing room

  (menu-bar-mode -1)            ; Disable the menu bar

  ;; Set up the visible bell
  (setq visible-bell t)

  (column-number-mode)
  (global-display-line-numbers-mode -1)
#+end_src
* パッケージ自動アップデート
#+BEGIN_SRC elisp :tangle yes
  ;; パッケージアーカイブ
  (setq gnutls-algorithm-priority "NORMAL:-VERS-TLS1.3")
  (eval-and-compile
    (require 'package)
    (customize-set-variable
     'package-archives '(("org" . "https://orgmode.org/elpa/")
			 ("melpa" . "https://melpa.org/packages/")
			 ("melpa-stable" . "https://mstable.elpa.org/packages/")
			 ("gnu" . "https://elpa.gnu.org/packages/")))
    (package-initialize)
    (unless package-archive-contents
      (package-refresh-contents))

    ;; Initialize use-package on non-Linux platforms
    (unless (package-installed-p 'use-package)
      (package-install 'use-package))

    (require 'use-package)
    (setq use-package-always-ensure t))

  ;; パッケージ自動アップデート
  (use-package auto-package-update
    :custom
    (auto-package-update-interval 7)
    (auto-package-update-prompt-before-update t)
    (auto-package-update-hide-results t)
    :config
    (auto-package-update-maybe)
    (auto-package-update-at-time "20:00"))
#+END_SRC

* EditorConfig
#+begin_src elisp :tangle yes
  ;; Editor Config
  ;; https://editorconfig.org/
  (use-package editorconfig
    :ensure t
    :config
    (editorconfig-mode 1))
#+end_src

;; Local Variables:
;; eval: (add-hook 'after-save-hook (lambda ()(if (y-or-n-p "Reload?")(load-file user-init-file))) nil t)
;; eval: (add-hook 'after-save-hook (lambda ()(if (y-or-n-p "Tangle?")(org-babel-tangle))) nil t)
;; End:
* より本物に近いターミナルエミュレータ
https://github.com/akermu/emacs-libvterm
** 前提条件
Cライブラリをコンパイルして利用するため、コンパイル環境を準備
*** Debian 系列
#+begin_src sh
  sudo apt install libtool
  sudo apt install libtool-bin
#+end_src
*** Haiku
#+begin_src sh
  pkgman install cmake
  pkgman install libtool
#+end_src
** パッケージ導入
#+begin_src elisp :tangle yes
  ;; より本物に近いターミナルエミュレータ
  (use-package vterm
    :unless (eq system-type 'windows-nt)
    :ensure t)
#+end_src
* 基本関数
#+BEGIN_SRC elisp :tangle yes
  ;; 基本関数
  (defun replace-in-string (what with in)
    (replace-regexp-in-string (regexp-quote what) with in nil 'literal))

  (defun safe-system-type-string ()
    (replace-in-string "/" "_" (prin1-to-string system-type)))

  (defun safe-host-name-string ()
    (replace-in-string "/" "_" (downcase (system-name))))

  (defun sys-base-name (prefix suffix)
    (concat prefix "-" (safe-system-type-string) suffix ))

  (defun host-base-name (prefix suffix)
    (concat prefix "-" (safe-host-name-string) suffix ))
#+END_SRC

* 外部プロセス更新ファイルのバッファ同期
#+BEGIN_SRC elisp :tangle yes
  ;; 外部プロセス更新ファイルのバッファ同期
  (setq make-backup-files nil)
  ;; https://takaxp.github.io/init.html#orgc2257142
  (when (require 'auto-save-buffers nil t)

    (defun my-ox-hugo-auto-saving-p ()
      (when (eq major-mode 'org-mode)
        (or (bound-and-true-p org-capture-mode) ;; when activating org-capture
            (and (fboundp 'org-entry-get)
                 (equal "" (org-entry-get (point) "EXPORT_FILE_NAME"))))))

    (defun my-auto-save-buffers ()
      (cond ((memq major-mode '(undo-tree-visualizer-mode diff-mode)) nil)
            ((string-match "Org Src" (buffer-name)) nil)
            ((let ((pt (point)))
               (and (string-match ".gpg" (buffer-name))
                    (not (eq pt 1))
                    (string-match (buffer-substring (- pt 1) pt) " "))) nil) ;; .gpg で半角スペースの後ろのブリッツでは自動保存しない．FIXME 半角スペース+行末
            ((my-ox-hugo-auto-saving-p) nil)
            (t
             (auto-save-buffers))))

    (run-with-idle-timer 1.6 t #'my-auto-save-buffers))

  (unless noninteractive
    (global-auto-revert-mode 1)
    ;; revert されるのが org バッファのとき，自動的にドロワをたたむ
    ;; カーソルが (point-max) に移動してしまう場合は非推奨
    (with-eval-after-load "org"
      (defun my-org-hide-drawers-all ()
        (when (eq major-mode 'org-mode)
          (org-cycle-hide-drawers 'all)))
      (add-hook 'after-revert-hook 'my-org-hide-drawers-all)))
#+END_SRC

* 最近訪れたファイル対応
#+BEGIN_SRC elisp :tangle yes
  ;; 最近訪れたファイル対応
  (defun recentf-base-name ()
    (host-base-name "recentf" ".dat"))

  (defun recentf-file-name ()
    (expand-file-name (locate-user-emacs-file (recentf-base-name))))

  (setq recentf-save-file (recentf-file-name))

  (recentf-mode 1)
  (setq recentf-max-menu-items 25)
  (setq recentf-max-saved-items 25)
  (global-set-key "\C-x\ \C-r" 'recentf-open-files)
#+END_SRC
* ido
* オプション
現在の起動オプションでは読み込ませたくないので、一時的に除外する。
これは、emacs の起動引数の役割を私が理解していないためである。

#+begin_src elisp :tangle yes
  (defun options-base-name ()
    (sys-base-name "options-experimental" ".el"))

  (defun options-file-name ()
    (expand-file-name (locate-user-emacs-file (options-base-name))))

  (setq custom-file (options-file-name))
  (if (file-exists-p custom-file)
      (load custom-file t nil nil))
#+end_src

*** DONE 他のホストと、衝突する恐れがある
単純に導入しただけでは、Nextcloudで共有している他のホストと衝突してしまう。
本来であれば、Nextcloudクライアント側でignore ファイルを共有して回避すべき問題である。
ホスト名を付加して衝突回避できるか要検討。
* 拡張選択範囲
#+BEGIN_SRC elisp :tangle yes
  ;; 拡張選択範囲
  (use-package expand-region
    :ensure t)
  (global-set-key (kbd "C-q") 'er/expand-region)
#+END_SRC

* コード補完
#+BEGIN_SRC elisp :tangle yes
  ;; コード補完
  (use-package company
    :ensure t)
#+END_SRC

* ミニバッファーの改善
詳しい解説は次のビデオにある https://www.youtube.com/watch?v=d3aaxOqwHhI
** vertico, marginalia
#+begin_src elisp :tangle yes
  ;; ミニバッファーの改善
  ;; https://github.com/minad/vertico
  (use-package vertico
    :ensure t
    :config
    (setq vertico-cycle t)
    (setq vertico-resize nil)
    (vertico-mode 1))

  ;; https://github.com/minad/marginalia
  (use-package marginalia
    :ensure t
    :config
    (marginalia-mode 1))

  ;; https://github.com/minad/consult
  (use-package consult
    :ensure t)
#+end_src

** consult
#+begin_src elisp :tangle yes
  ;; Example configuration for Consult
  (use-package consult
    ;; Replace bindings. Lazily loaded by `use-package'.
    :bind (;; C-c bindings in `mode-specific-map'
           ("C-c M-x" . consult-mode-command)
           ("C-c h" . consult-history)
           ("C-c k" . consult-kmacro)
           ("C-c m" . consult-man)
           ("C-c i" . consult-info)
           ([remap Info-search] . consult-info)
           ;; C-x bindings in `ctl-x-map'
           ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
           ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
           ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
           ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
           ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
           ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
           ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
           ;; Custom M-# bindings for fast register access
           ("M-#" . consult-register-load)
           ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
           ("C-M-#" . consult-register)
           ;; Other custom bindings
           ("M-y" . consult-yank-pop)                ;; orig. yank-pop
           ;; M-g bindings in `goto-map'
           ("M-g e" . consult-compile-error)
           ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
           ("M-g g" . consult-goto-line)             ;; orig. goto-line
           ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
           ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
           ("M-g m" . consult-mark)
           ("M-g k" . consult-global-mark)
           ("M-g i" . consult-imenu)
           ("M-g I" . consult-imenu-multi)
           ;; M-s bindings in `search-map'
           ("M-s d" . consult-find)                  ;; Alternative: consult-fd
           ("M-s c" . consult-locate)
           ("M-s g" . consult-grep)
           ("M-s G" . consult-git-grep)
           ("M-s r" . consult-ripgrep)
           ("M-s l" . consult-line)
           ("M-s L" . consult-line-multi)
           ("M-s k" . consult-keep-lines)
           ("M-s u" . consult-focus-lines)
           ;; Isearch integration
           ("M-s e" . consult-isearch-history)
           :map isearch-mode-map
           ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
           ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
           ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
           ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
           ;; Minibuffer history
           :map minibuffer-local-map
           ("M-s" . consult-history)                 ;; orig. next-matching-history-element
           ("M-r" . consult-history))                ;; orig. previous-matching-history-element

    ;; Enable automatic preview at point in the *Completions* buffer. This is
    ;; relevant when you use the default completion UI.
    :hook (completion-list-mode . consult-preview-at-point-mode)

    ;; The :init configuration is always executed (Not lazy)
    :init

    ;; Optionally configure the register formatting. This improves the register
    ;; preview for `consult-register', `consult-register-load',
    ;; `consult-register-store' and the Emacs built-ins.
    (setq register-preview-delay 0.5
          register-preview-function #'consult-register-format)

    ;; Optionally tweak the register preview window.
    ;; This adds thin lines, sorting and hides the mode line of the window.
    (advice-add #'register-preview :override #'consult-register-window)

    ;; Use Consult to select xref locations with preview
    (setq xref-show-xrefs-function #'consult-xref
          xref-show-definitions-function #'consult-xref)

    ;; Configure other variables and modes in the :config section,
    ;; after lazily loading the package.
    :config

    ;; Optionally configure preview. The default value
    ;; is 'any, such that any key triggers the preview.
    ;; (setq consult-preview-key 'any)
    ;; (setq consult-preview-key "M-.")
    ;; (setq consult-preview-key '("S-<down>" "S-<up>"))
    ;; For some commands and buffer sources it is useful to configure the
    ;; :preview-key on a per-command basis using the `consult-customize' macro.
    (consult-customize
     consult-theme :preview-key '(:debounce 0.2 any)
     consult-ripgrep consult-git-grep consult-grep
     consult-bookmark consult-recent-file consult-xref
     consult--source-bookmark consult--source-file-register
     consult--source-recent-file consult--source-project-recent-file
     ;; :preview-key "M-."
     :preview-key '(:debounce 0.4 any))

    ;; Optionally configure the narrowing key.
    ;; Both < and C-+ work reasonably well.
    (setq consult-narrow-key "<") ;; "C-+"

    ;; Optionally make narrowing help available in the minibuffer.
    ;; You may want to use `embark-prefix-help-command' or which-key instead.
    ;; (keymap-set consult-narrow-map (concat consult-narrow-key " ?") #'consult-narrow-help)
    )
#+end_src

** embark
#+begin_src elisp :tangle yes
  ;; https://github.com/oantolin/embark/
  (use-package embark
    :ensure t

    :bind
    (("C-." . embark-act)         ;; pick some comfortable binding
     ("C-;" . embark-dwim)        ;; good alternative: M-.
     ("C-h B" . embark-bindings)) ;; alternative for `describe-bindings'

    :init

    ;; Optionally replace the key help with a completing-read interface
    (setq prefix-help-command #'embark-prefix-help-command)

    ;; Show the Embark target at point via Eldoc. You may adjust the
    ;; Eldoc strategy, if you want to see the documentation from
    ;; multiple providers. Beware that using this can be a little
    ;; jarring since the message shown in the minibuffer can be more
    ;; than one line, causing the modeline to move up and down:

    ;; (add-hook 'eldoc-documentation-functions #'embark-eldoc-first-target)
    ;; (setq eldoc-documentation-strategy #'eldoc-documentation-compose-eagerly)

    :config

    ;; Hide the mode line of the Embark live/completions buffers
    (add-to-list 'display-buffer-alist
                 '("\\`\\*Embark Collect \\(Live\\|Completions\\)\\*"
                   nil
                   (window-parameters (mode-line-format . none)))))

  ;; Consult users will also want the embark-consult package.
  (use-package embark-consult
    :ensure t ; only need to install it, embark loads it after consult if found
    :hook
    (embark-collect-mode . consult-preview-at-point-mode))
#+end_src

* Corf
#+begin_src elisp :tangle yes
  ;; https://github.com/minad/corfu
  (use-package corfu
    ;; Optional customizations
    ;; :custom
    ;; (corfu-cycle t)                ;; Enable cycling for `corfu-next/previous'
    ;; (corfu-auto t)                 ;; Enable auto completion
    ;; (corfu-quit-at-boundary nil)   ;; Never quit at completion boundary
    ;; (corfu-quit-no-match nil)      ;; Never quit, even if there is no match
    ;; (corfu-preview-current nil)    ;; Disable current candidate preview
    ;; (corfu-preselect 'prompt)      ;; Preselect the prompt
    ;; (corfu-on-exact-match nil)     ;; Configure handling of exact matches

    ;; Enable Corfu only for certain modes. See also `global-corfu-modes'.
    ;; :hook ((prog-mode . corfu-mode)
    ;;        (shell-mode . corfu-mode)
    ;;        (eshell-mode . corfu-mode))

    ;; Recommended: Enable Corfu globally.  This is recommended since Dabbrev can
    ;; be used globally (M-/).  See also the customization variable
    ;; `global-corfu-modes' to exclude certain modes.
    :init
    (global-corfu-mode))

  ;; A few more useful configurations...
  (use-package emacs
    :custom
    ;; TAB cycle if there are only few candidates
    ;; (completion-cycle-threshold 3)

    ;; Enable indentation+completion using the TAB key.
    ;; `completion-at-point' is often bound to M-TAB.
    (tab-always-indent 'complete)

    ;; Emacs 30 and newer: Disable Ispell completion function.
    ;; Try `cape-dict' as an alternative.
    (text-mode-ispell-word-completion nil)

    ;; Hide commands in M-x which do not apply to the current mode.  Corfu
    ;; commands are hidden, since they are not used via M-x. This setting is
    ;; useful beyond Corfu.
    (read-extended-command-predicate #'command-completion-default-include-p))
#+end_src
* ディレクトリ表示の簡素化
https://emacs.stackexchange.com/questions/27912/dired-sort-and-hide-by-default
#+begin_src elisp
  ;; ディレクトリ表示の簡素化
  ;; https://emacs.stackexchange.com/questions/27912/dired-sort-and-hide-by-default
  (add-hook 'dired-mode-hook
            (lambda ()
              (dired-hide-details-mode 1)
              (dired-sort-toggle-or-edit)))
#+end_src
* Magit 設定
#+BEGIN_SRC elisp :tangle yes
  ;; Magit 設定
  (use-package magit
    :ensure t
    :pin melpa)

  ;; https://joppot.info/posts/f3007a42-5ba2-4060-90d4-496697413cf9
  (use-package diff-hl
    :ensure t
    :init
    (global-diff-hl-mode)
    (add-hook 'dired-mode-hook 'diff-hl-dired-mode)
    (unless (window-system) (diff-hl-margin-mode))
    :custom-face
    (diff-hl-change ((t (:background "#8adf80"))))
    (diff-hl-delete ((t (:background "#ff8f88"))))
    (diff-hl-insert ((t (:background "#bfc9ff"))))
    :config
    (add-hook 'magit-pre-refresh-hook 'diff-hl-magit-pre-refresh)
    (add-hook 'magit-post-refresh-hook 'diff-hl-magit-post-refresh))
#+END_SRC

* Lisp ファミリ基本設定
#+BEGIN_SRC elisp :tangle yes
  ;; Lisp ファミリ基本設定
  (show-paren-mode t)
  (use-package paredit
    :ensure t
    :commands enable-paredit-mode
    :hook ((emacs-lisp-mode
            org-mode)
           . enable-paredit-mode))

  (use-package smartparens :ensure t)
  (use-package rainbow-delimiters :ensure t)
#+END_SRC

** emacs lisp
#+BEGIN_SRC elisp :tangle yes
  ;; emacs lisp
  (add-hook 'emacs-lisp-mode-hook 'paredit-mode)
  (add-hook 'emacs-lisp-mode-hook 'rainbow-delimiters-mode)
  ;; (add-hook 'emacs-lisp-mode-hook 'company-mode)
  ;; (add-hook 'emacs-lisp-mode-hook 'subword-mode)
  ;; (add-hook 'emacs-lisp-mode-hook 'aggressive-indent-mode)

  (eval-after-load 'inferior-emacs-lisp-mode
    '(progn
       (add-hook 'ielm-mode-hook 'paredit-mode)
       (define-key paredit-mode-map (kbd "RET") nil)
       (define-key paredit-mode-map (kbd "C-j") 'paredit-newline)))

#+END_SRC

* DONE 横に広がりすぎて編集しづらい。auto wrapp で単語境界で区切るのは日本語には合わない
=C-x x t=
=toggle-truncate-lines=
でトグルできるのだが、継続行が先頭に来て見づらくなる。
そこで次の記事を参考にしてみた。
https://zenn.dev/ebang/articles/231106_emacs-markdown
#+begin_src elisp :tangle yes
  (use-package markdown-mode
    :mode ("\\.md\\'" . markdown-mode)
    :init
    (add-hook 'markdown-mode-hook #'turn-off-auto-fill)
    (add-hook 'markdown-mode-hook #'turn-on-visual-line-mode))

  (unless (version< emacs-version "29.1")
    (use-package word-wrap-mode
      :hook (visual-line-mode . word-wrap-whitespace-mode)
      :config
      (add-to-list 'word-wrap-whitespace-characters ?\])))

  ;; (use-package visual-fill-column
  ;;   :hook (visual-line-mode . visual-fill-column-mode)
  ;;   :init
  ;;   (setq visual-line-fringe-indicators '(left-curly-arrow nil))
  ;;   :config
  ;;   (setq visual-fill-column-width 120))

  (use-package adaptive-wrap
    :hook (visual-line-mode . adaptive-wrap-prefix-mode))
#+end_src

* Org
** 近代化
#+begin_src elisp :tangle yes
  (use-package org-modern
    :ensure t
    :hook ((org-mode . org-modern-mode)))
#+end_src

** =<s <tab>= でブロック文のテンプレートを挿入
#+BEGIN_SRC elisp :tangle yes
  ;; <s <tab> でブロック文のテンプレートを挿入
  (require 'org-tempo)
#+END_SRC

** デフォルトのbabelではシェルは禁止されているの使えるようにする
#+begin_src elisp :tangle yes
  ;; デフォルトのbabelではシェルは禁止されているの使えるようにする
  (org-babel-do-load-languages
   'org-babel-load-languages
   '(
     (shell . t)
     (ruby . t)
     (python . t)
     ))
#+end_src
** DONE 起動時に、自動で折りたたむ設定はどうだったっけ
参考: https://takaxp.github.io/org-ja.html
#+begin_src
#+STARTUP: content
#+end_src
#+
** =open-url-at-point= で開かれるブラウザの設定
#+begin_src elisp :tangle yes
(setq browse-url-browser-function 'eww-browse-url)
#+end_src

* お遊び
** TODO ポモドーロタイマに使用する音源を物色中
Windows の検索パスは別途検討
#+begin_src elisp :results list
  (let ((all-sounds
         (directory-files-recursively "/usr/share/sounds/sound-icons/" "\\.wav$" nil)))
    (dolist (snd all-sounds)
      (play-sound-file snd))
    all-sounds)
#+end_src

#+begin_src elisp :results list
  (let ((all-sounds
         (directory-files-recursively "C:/Windows" "\\.wav$" nil)))
    ;; (dolist (snd all-sounds)
    ;;   (play-sound-file snd))
    all-sounds)
#+end_src

#+RESULTS:
- c:/Windows/Media/dm/Windows Background.wav
- c:/Windows/Media/dm/Windows Foreground.wav
- c:/Windows/Media/dm/Windows Hardware Fail.wav
- c:/Windows/Media/dm/Windows Hardware Insert.wav
- c:/Windows/Media/dm/Windows Hardware Remove.wav
- c:/Windows/Media/dm/Windows Notify Calendar.wav
- c:/Windows/Media/dm/Windows Notify Email.wav
- c:/Windows/Media/dm/Windows Notify Messaging.wav
- c:/Windows/Media/dm/Windows Notify System Generic.wav
- c:/Windows/Media/dm/Windows User Account Control.wav
- c:/Windows/Media/Alarm01.wav
- c:/Windows/Media/Alarm02.wav
- c:/Windows/Media/Alarm03.wav
- c:/Windows/Media/Alarm04.wav
- c:/Windows/Media/Alarm05.wav
- c:/Windows/Media/Alarm06.wav
- c:/Windows/Media/Alarm07.wav
- c:/Windows/Media/Alarm08.wav
- c:/Windows/Media/Alarm09.wav
- c:/Windows/Media/Alarm10.wav
- c:/Windows/Media/Ring01.wav
- c:/Windows/Media/Ring02.wav
- c:/Windows/Media/Ring03.wav
- c:/Windows/Media/Ring04.wav
- c:/Windows/Media/Ring05.wav
- c:/Windows/Media/Ring06.wav
- c:/Windows/Media/Ring07.wav
- c:/Windows/Media/Ring08.wav
- c:/Windows/Media/Ring09.wav
- c:/Windows/Media/Ring10.wav
- c:/Windows/Media/Speech Disambiguation.wav
- c:/Windows/Media/Speech Misrecognition.wav
- c:/Windows/Media/Speech Off.wav
- c:/Windows/Media/Speech On.wav
- c:/Windows/Media/Speech Sleep.wav
- c:/Windows/Media/Windows Background.wav
- c:/Windows/Media/Windows Balloon.wav
- c:/Windows/Media/Windows Battery Critical.wav
- c:/Windows/Media/Windows Battery Low.wav
- c:/Windows/Media/Windows Critical Stop.wav
- c:/Windows/Media/Windows Default.wav
- c:/Windows/Media/Windows Ding.wav
- c:/Windows/Media/Windows Error.wav
- c:/Windows/Media/Windows Exclamation.wav
- c:/Windows/Media/Windows Feed Discovered.wav
- c:/Windows/Media/Windows Foreground.wav
- c:/Windows/Media/Windows Hardware Fail.wav
- c:/Windows/Media/Windows Hardware Insert.wav
- c:/Windows/Media/Windows Hardware Remove.wav
- c:/Windows/Media/Windows Information Bar.wav
- c:/Windows/Media/Windows Logoff Sound.wav
- c:/Windows/Media/Windows Logon.wav
- c:/Windows/Media/Windows Menu Command.wav
- c:/Windows/Media/Windows Message Nudge.wav
- c:/Windows/Media/Windows Minimize.wav
- c:/Windows/Media/Windows Navigation Start.wav
- c:/Windows/Media/Windows Notify Calendar.wav
- c:/Windows/Media/Windows Notify Email.wav
- c:/Windows/Media/Windows Notify Messaging.wav
- c:/Windows/Media/Windows Notify System Generic.wav
- c:/Windows/Media/Windows Notify.wav
- c:/Windows/Media/Windows Pop-up Blocked.wav
- c:/Windows/Media/Windows Print complete.wav
- c:/Windows/Media/Windows Proximity Connection.wav
- c:/Windows/Media/Windows Proximity Notification.wav
- c:/Windows/Media/Windows Recycle.wav
- c:/Windows/Media/Windows Restore.wav
- c:/Windows/Media/Windows Ringin.wav
- c:/Windows/Media/Windows Ringout.wav
- c:/Windows/Media/Windows Shutdown.wav
- c:/Windows/Media/Windows Startup.wav
- c:/Windows/Media/Windows Unlock.wav
- c:/Windows/Media/Windows User Account Control.wav
- c:/Windows/Media/chimes.wav
- c:/Windows/Media/chord.wav
- c:/Windows/Media/ding.wav
- c:/Windows/Media/notify.wav
- c:/Windows/Media/recycle.wav
- c:/Windows/Media/ringout.wav
- c:/Windows/Media/tada.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/Dictation/BasicCancelledEarcon.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/Dictation/BasicDoneListeningEarcon.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/Dictation/BasicListeningEarcon.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdAccentPicker.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdFunction.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdFunctionModernUX.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdKeyTap.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdKeyTapModernUX.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdSpaceBarModernUX.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdSpacebar.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/InputApp/Assets/KbdSwipeGesture.wav
- c:/Windows/SystemApps/MicrosoftWindows.Client.CBS_cw5n1h2txyewy/ScreenClipping/Assets/Sounds/camerashutter.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-ie-internetexplorer_31bf3856ad364e35_11.0.22621.3527_none_52f66545bf10ea29/Windows Feed Discovered.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-ie-internetexplorer_31bf3856ad364e35_11.0.22621.3527_none_52f66545bf10ea29/Windows Information Bar.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-ie-internetexplorer_31bf3856ad364e35_11.0.22621.3527_none_52f66545bf10ea29/Windows Navigation Start.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-ie-internetexplorer_31bf3856ad364e35_11.0.22621.3527_none_52f66545bf10ea29/Windows Pop-up Blocked.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Background.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Foreground.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Hardware Fail.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Hardware Insert.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Hardware Remove.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Notify Calendar.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Notify Email.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Notify Messaging.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows Notify System Generic.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds-dm_31bf3856ad364e35_10.0.22621.1_none_a9a06b326661fac0/Windows User Account Control.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm01.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm02.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm03.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm04.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm05.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm06.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm07.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm08.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm09.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Alarm10.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring01.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring02.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring03.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring04.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring05.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring06.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring07.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring08.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring09.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Ring10.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Background.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Balloon.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Battery Critical.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Battery Low.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Critical Stop.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Default.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Ding.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Error.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Exclamation.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Foreground.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Hardware Fail.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Hardware Insert.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Hardware Remove.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Logoff Sound.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Logon.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Menu Command.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Message Nudge.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Minimize.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Notify Calendar.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Notify Email.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Notify Messaging.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Notify System Generic.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Notify.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Print complete.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Proximity Connection.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Proximity Notification.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Recycle.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Restore.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Ringin.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Ringout.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Shutdown.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Startup.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows Unlock.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/Windows User Account Control.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/chimes.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/chord.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/ding.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/notify.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/recycle.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/ringout.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-shell-sounds_31bf3856ad364e35_10.0.22621.3527_none_f6eecd7c3127689e/tada.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.3672_none_fbe0e4c2c76d8bb2/Speech Disambiguation.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.3672_none_fbe0e4c2c76d8bb2/Speech Misrecognition.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.3672_none_fbe0e4c2c76d8bb2/Speech Off.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.3672_none_fbe0e4c2c76d8bb2/Speech On.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.3672_none_fbe0e4c2c76d8bb2/Speech Sleep.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.4249_none_fc088602c7508077/Speech Disambiguation.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.4249_none_fc088602c7508077/Speech Misrecognition.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.4249_none_fc088602c7508077/Speech Off.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.4249_none_fc088602c7508077/Speech On.wav
- c:/Windows/WinSxS/amd64_microsoft-windows-speech-userexperience_31bf3856ad364e35_10.0.22621.4249_none_fc088602c7508077/Speech Sleep.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/Dictation/BasicCancelledEarcon.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/Dictation/BasicDoneListeningEarcon.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/Dictation/BasicListeningEarcon.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdAccentPicker.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdFunction.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdFunctionModernUX.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdKeyTap.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdKeyTapModernUX.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdSpaceBarModernUX.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdSpacebar.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/InputApp/Assets/KbdSwipeGesture.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4111_none_0c5d079de5c7d956/CBS/ScreenClipping/Assets/Sounds/camerashutter.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/Dictation/BasicCancelledEarcon.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/Dictation/BasicDoneListeningEarcon.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/Dictation/BasicListeningEarcon.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdAccentPicker.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdFunction.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdFunctionModernUX.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdKeyTap.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdKeyTapModernUX.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdSpaceBarModernUX.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdSpacebar.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/InputApp/Assets/KbdSwipeGesture.wav
- c:/Windows/WinSxS/amd64_userexperience-desktop_31bf3856ad364e35_10.0.22621.4249_none_0c54824fe5ce0e54/CBS/ScreenClipping/Assets/Sounds/camerashutter.wav

#+RESULTS(Linux):
- /usr/share/sounds/sound-icons/canary-long.wav
- /usr/share/sounds/sound-icons/cembalo-1.wav
- /usr/share/sounds/sound-icons/cembalo-10.wav
- /usr/share/sounds/sound-icons/cembalo-11.wav
- /usr/share/sounds/sound-icons/cembalo-12.wav
- /usr/share/sounds/sound-icons/cembalo-2.wav
- /usr/share/sounds/sound-icons/cembalo-3.wav
- /usr/share/sounds/sound-icons/cembalo-6.wav
- /usr/share/sounds/sound-icons/chord-7.wav
- /usr/share/sounds/sound-icons/cockchafer-gentleman-1.wav
- /usr/share/sounds/sound-icons/cymbaly-1.wav
- /usr/share/sounds/sound-icons/electric-piano-3.wav
- /usr/share/sounds/sound-icons/glass-water-1.wav
- /usr/share/sounds/sound-icons/guitar-12.wav
- /usr/share/sounds/sound-icons/guitar-13.wav
- /usr/share/sounds/sound-icons/gummy-cat-2.wav
- /usr/share/sounds/sound-icons/klavichord-4.wav
- /usr/share/sounds/sound-icons/percussion-10.wav
- /usr/share/sounds/sound-icons/percussion-12.wav
- /usr/share/sounds/sound-icons/percussion-28.wav
- /usr/share/sounds/sound-icons/percussion-50.wav
- /usr/share/sounds/sound-icons/piano-3.wav
- /usr/share/sounds/sound-icons/pipe.wav
- /usr/share/sounds/sound-icons/pisk-down-cink.wav
- /usr/share/sounds/sound-icons/pisk-down.wav
- /usr/share/sounds/sound-icons/pisk-up-cink.wav
- /usr/share/sounds/sound-icons/pisk-up.wav
- /usr/share/sounds/sound-icons/prompt.wav
- /usr/share/sounds/sound-icons/trumpet-1.wav
- /usr/share/sounds/sound-icons/trumpet-12.wav
- /usr/share/sounds/sound-icons/violoncello-7.wav
- /usr/share/sounds/sound-icons/xylofon.wav

** eww がローカルのファイルを開けるか
#+begin_src elisp
(eww-browse-url "file:///usr/local/share/GNUstep/Documentation/Developer/Base/ProgrammingManual/gs-base/index.html")
#+end_src

** string-matchの実験
#+begin_src elisp
  (string-match-p "\\.wav$"
		  "/usr/share/sounds/sound-icons/canary-long.wav")
  (string-match-p "^file:///"
		  "file:///usr/local/share/GNUstep/Documentation/Developer/Base/ProgrammingManual/gs-base/index.html")
#+end_src

* ポモドーロタイマー
[[https://systemcrafters.net/emacs-shorts/pomodoro-timer/]]
#+begin_src elisp :tangle yes
  ;; https://systemcrafters.net/emacs-shorts/pomodoro-timer/
  (setq org-clock-sound "/usr/share/sounds/sound-icons/xylofon.wav")
  ;; C-c C-x ;
  (org-timer-set-timer 25)
#+end_src

#+RESULTS:
: /usr/share/sounds/sound-icons/xylofon.wav
* キーストローク表示
#+begin_src elisp :tangle yes
  ;; キーストローク表示
  ;; https://github.com/tarsius/keycast
  (use-package keycast
    :ensure t)
#+end_src
* 日本語フォントの設定
** 使用できるフォント名の確認
#+begin_src elisp :results list
  (seq-uniq (sort (font-family-list) 'string<) 'string=)
#+end_src

*** RESULTS(Haiku):
- Bitstream Charter
- Cantarell
- DejaVu Math TeX Gyre
- DejaVu Sans
- DejaVu Sans Mono
- DejaVu Serif
- Fira Mono
- Fira Sans
- Fira Sans Condensed
- FontAwesome
- Material Icons
- Noto Sans
- Noto Sans CJK JP
- Noto Sans Display
- Noto Sans Mono
- Noto Sans Mono CJK JP
- Noto Sans Symbols
- Noto Sans Symbols 2
- Noto Sans Thai
- Noto Serif
- Noto Serif Display
- Noto Serif Thai
- Source Code Pro
- Source Sans Pro
- Source Serif Pro
- Ubuntu
- Ubuntu Condensed
- Ubuntu Mono
- Weather Icons
- all-the-icons
- file-icons
- github-octicons

*** RESULTS(Windows):
- Arial
- Arial Black
- BIZ UDPゴシック
- BIZ UDP明朝 Medium
- BIZ UDゴシック
- BIZ UD明朝 Medium
- Bahnschrift
- Bahnschrift Condensed
- Bahnschrift Light
- Bahnschrift Light Condensed
- Bahnschrift Light SemiCondensed
- Bahnschrift SemiBold
- Bahnschrift SemiBold Condensed
- Bahnschrift SemiBold SemiConden
- Bahnschrift SemiCondensed
- Bahnschrift SemiLight
- Bahnschrift SemiLight Condensed
- Bahnschrift SemiLight SemiConde
- Calibri
- Calibri Light
- Cambria
- Cambria Math
- Candara
- Candara Light
- Cantarell
- Cascadia Code
- Cascadia Code ExtraLight
- Cascadia Code Light
- Cascadia Code SemiBold
- Cascadia Code SemiLight
- Cascadia Mono
- Cascadia Mono ExtraLight
- Cascadia Mono Light
- Cascadia Mono SemiBold
- Cascadia Mono SemiLight
- Comic Sans MS
- Consolas
- Constantia
- Corbel
- Corbel Light
- Courier
- Courier New
- Ebrima
- Fira Code
- Fira Code Light
- Fira Code Medium
- Fira Code Retina
- Fira Code SemiBold
- FixedSys
- FontAwesome
- Franklin Gothic Medium
- Gabriola
- Gadugi
- Georgia
- HackGen
- HackGen Console
- HackGen Console NF
- HackGen Console NFJ
- HackGen35
- HackGen35 Console
- HackGen35 Console NF
- HackGen35 Console NFJ
- HoloLens MDL2 Assets
- Impact
- Ink Free
- Iosevka NF
- Iosevka NF ExtraBold
- Iosevka NF ExtraBold Obl
- Iosevka NF ExtraLight
- Iosevka NF ExtraLight Obl
- Iosevka NF Heavy
- Iosevka NF Heavy Obl
- Iosevka NF Light
- Iosevka NF Light Obl
- Iosevka NF Medium
- Iosevka NF Medium Obl
- Iosevka NF Obl
- Iosevka NF SemiBold
- Iosevka NF SemiBold Obl
- Iosevka NF Thin
- Iosevka NF Thin Obl
- Iosevka NFM
- Iosevka NFM ExtraBold
- Iosevka NFM ExtraBold Obl
- Iosevka NFM ExtraLight
- Iosevka NFM ExtraLight Obl
- Iosevka NFM Heavy
- Iosevka NFM Heavy Obl
- Iosevka NFM Light
- Iosevka NFM Light Obl
- Iosevka NFM Medium
- Iosevka NFM Medium Obl
- Iosevka NFM Obl
- Iosevka NFM SemiBold
- Iosevka NFM SemiBold Obl
- Iosevka NFM Thin
- Iosevka NFM Thin Obl
- Iosevka NFP
- Iosevka NFP ExtraBold
- Iosevka NFP ExtraBold Obl
- Iosevka NFP ExtraLight
- Iosevka NFP ExtraLight Obl
- Iosevka NFP Heavy
- Iosevka NFP Heavy Obl
- Iosevka NFP Light
- Iosevka NFP Light Obl
- Iosevka NFP Medium
- Iosevka NFP Medium Obl
- Iosevka NFP Obl
- Iosevka NFP SemiBold
- Iosevka NFP SemiBold Obl
- Iosevka NFP Thin
- Iosevka NFP Thin Obl
- IosevkaTerm NF
- IosevkaTerm NF ExtraBold
- IosevkaTerm NF ExtraBold Obl
- IosevkaTerm NF ExtraLight
- IosevkaTerm NF ExtraLight Obl
- IosevkaTerm NF Heavy
- IosevkaTerm NF Heavy Obl
- IosevkaTerm NF Light
- IosevkaTerm NF Light Obl
- IosevkaTerm NF Medium
- IosevkaTerm NF Medium Obl
- IosevkaTerm NF Obl
- IosevkaTerm NF SemiBold
- IosevkaTerm NF SemiBold Obl
- IosevkaTerm NF Thin
- IosevkaTerm NF Thin Obl
- IosevkaTerm NFM
- IosevkaTerm NFM ExtraBold
- IosevkaTerm NFM ExtraBold Obl
- IosevkaTerm NFM ExtraLight
- IosevkaTerm NFM ExtraLight Obl
- IosevkaTerm NFM Heavy
- IosevkaTerm NFM Heavy Obl
- IosevkaTerm NFM Light
- IosevkaTerm NFM Light Obl
- IosevkaTerm NFM Medium
- IosevkaTerm NFM Medium Obl
- IosevkaTerm NFM Obl
- IosevkaTerm NFM SemiBold
- IosevkaTerm NFM SemiBold Obl
- IosevkaTerm NFM Thin
- IosevkaTerm NFM Thin Obl
- IosevkaTerm NFP
- IosevkaTerm NFP ExtraBold
- IosevkaTerm NFP ExtraBold Obl
- IosevkaTerm NFP ExtraLight
- IosevkaTerm NFP ExtraLight Obl
- IosevkaTerm NFP Heavy
- IosevkaTerm NFP Heavy Obl
- IosevkaTerm NFP Light
- IosevkaTerm NFP Light Obl
- IosevkaTerm NFP Medium
- IosevkaTerm NFP Medium Obl
- IosevkaTerm NFP Obl
- IosevkaTerm NFP SemiBold
- IosevkaTerm NFP SemiBold Obl
- IosevkaTerm NFP Thin
- IosevkaTerm NFP Thin Obl
- IosevkaTermSlab NF
- IosevkaTermSlab NF ExtraBold
- IosevkaTermSlab NF ExtraBold Ob
- IosevkaTermSlab NF Light
- IosevkaTermSlab NF Light Obl
- IosevkaTermSlab NF Medium
- IosevkaTermSlab NF Medium Obl
- IosevkaTermSlab NF Obl
- IosevkaTermSlab NFM
- IosevkaTermSlab NFM ExtraBold
- IosevkaTermSlab NFM ExtraBold O
- IosevkaTermSlab NFM Light
- IosevkaTermSlab NFM Light Obl
- IosevkaTermSlab NFM Medium
- IosevkaTermSlab NFM Medium Obl
- IosevkaTermSlab NFM Obl
- IosevkaTermSlab NFP
- IosevkaTermSlab NFP ExtraBold
- IosevkaTermSlab NFP ExtraBold O
- IosevkaTermSlab NFP Light
- IosevkaTermSlab NFP Light Obl
- IosevkaTermSlab NFP Medium
- IosevkaTermSlab NFP Medium Obl
- IosevkaTermSlab NFP Obl
- Javanese Text
- Leelawadee UI
- Leelawadee UI Semilight
- Lucida Console
- Lucida Sans Unicode
- MS Sans Serif
- MS Serif
- MS UI Gothic
- MV Boli
- Malgun Gothic
- Malgun Gothic Semilight
- Marlett
- Material Icons
- Meiryo UI
- Microsoft Himalaya
- Microsoft JhengHei
- Microsoft JhengHei Light
- Microsoft JhengHei UI
- Microsoft JhengHei UI Light
- Microsoft New Tai Lue
- Microsoft PhagsPa
- Microsoft Sans Serif
- Microsoft Tai Le
- Microsoft YaHei
- Microsoft YaHei Light
- Microsoft YaHei UI
- Microsoft YaHei UI Light
- Microsoft Yi Baiti
- MingLiU-ExtB
- MingLiU_HKSCS-ExtB
- Modern
- Mongolian Baiti
- Myanmar Text
- NSimSun
- Nirmala UI
- Nirmala UI Semilight
- Noto Sans CJK HK
- Noto Sans CJK HK Black
- Noto Sans CJK HK DemiLight
- Noto Sans CJK HK Light
- Noto Sans CJK HK Medium
- Noto Sans CJK HK Thin
- Noto Sans CJK JP
- Noto Sans CJK JP Black
- Noto Sans CJK JP DemiLight
- Noto Sans CJK JP Light
- Noto Sans CJK JP Medium
- Noto Sans CJK JP Thin
- Noto Sans CJK KR
- Noto Sans CJK KR Black
- Noto Sans CJK KR DemiLight
- Noto Sans CJK KR Light
- Noto Sans CJK KR Medium
- Noto Sans CJK KR Thin
- Noto Sans CJK SC
- Noto Sans CJK SC Black
- Noto Sans CJK SC DemiLight
- Noto Sans CJK SC Light
- Noto Sans CJK SC Medium
- Noto Sans CJK SC Thin
- Noto Sans CJK TC
- Noto Sans CJK TC Black
- Noto Sans CJK TC DemiLight
- Noto Sans CJK TC Light
- Noto Sans CJK TC Medium
- Noto Sans CJK TC Thin
- Noto Sans Mono CJK HK
- Noto Sans Mono CJK JP
- Noto Sans Mono CJK KR
- Noto Sans Mono CJK SC
- Noto Sans Mono CJK TC
- Noto Serif CJK JP
- Noto Serif CJK JP Black
- Noto Serif CJK JP ExtraLight
- Noto Serif CJK JP Light
- Noto Serif CJK JP Medium
- Noto Serif CJK JP SemiBold
- Noto Serif CJK KR
- Noto Serif CJK KR Black
- Noto Serif CJK KR ExtraLight
- Noto Serif CJK KR Light
- Noto Serif CJK KR Medium
- Noto Serif CJK KR SemiBold
- Noto Serif CJK SC
- Noto Serif CJK SC Black
- Noto Serif CJK SC ExtraLight
- Noto Serif CJK SC Light
- Noto Serif CJK SC Medium
- Noto Serif CJK SC SemiBold
- Noto Serif CJK TC
- Noto Serif CJK TC Black
- Noto Serif CJK TC ExtraLight
- Noto Serif CJK TC Light
- Noto Serif CJK TC Medium
- Noto Serif CJK TC SemiBold
- PMingLiU-ExtB
- Palatino Linotype
- Roman
- Sans Serif Collection
- Script
- Segoe Fluent Icons
- Segoe MDL2 Assets
- Segoe Print
- Segoe Script
- Segoe UI
- Segoe UI Black
- Segoe UI Emoji
- Segoe UI Historic
- Segoe UI Light
- Segoe UI Semibold
- Segoe UI Semilight
- Segoe UI Symbol
- Segoe UI Variable Display
- Segoe UI Variable Display Light
- Segoe UI Variable Display Semib
- Segoe UI Variable Display Semil
- Segoe UI Variable Small
- Segoe UI Variable Small Light
- Segoe UI Variable Small Semibol
- Segoe UI Variable Small Semilig
- Segoe UI Variable Text
- Segoe UI Variable Text Light
- Segoe UI Variable Text Semibold
- Segoe UI Variable Text Semiligh
- SimSun
- SimSun-ExtB
- SimSun-ExtG
- Sitka Banner
- Sitka Banner Semibold
- Sitka Display
- Sitka Display Semibold
- Sitka Heading
- Sitka Heading Semibold
- Sitka Small
- Sitka Small Semibold
- Sitka Subheading
- Sitka Subheading Semibold
- Sitka Text
- Sitka Text Semibold
- Small Fonts
- Sylfaen
- Symbol
- Symbols Nerd Font Mono
- System
- Tahoma
- Terminal
- Times New Roman
- Trebuchet MS
- UD デジタル 教科書体 N-B
- UD デジタル 教科書体 N-R
- UD デジタル 教科書体 NK-B
- UD デジタル 教科書体 NK-R
- UD デジタル 教科書体 NP-B
- UD デジタル 教科書体 NP-R
- Verdana
- Weather Icons
- Webdings
- Wingdings
- Yu Gothic UI
- Yu Gothic UI Light
- Yu Gothic UI Semibold
- Yu Gothic UI Semilight
- all-the-icons
- file-icons
- github-octicons
- メイリオ
- 游ゴシック
- 游ゴシック Light
- 游ゴシック Medium
- 游明朝
- 游明朝 Demibold
- 游明朝 Light
- ＭＳ ゴシック
- ＭＳ 明朝
- ＭＳ Ｐゴシック
- ＭＳ Ｐ明朝

*** RESULTS(LINUX):
- Abyssinica SIL
- Ani
- AnjaliOldLipi
- Bitstream Charter
- C059
- Cantarell
- Century Schoolbook L
- Chandas
- Chilanka
- Courier
- Courier 10 Pitch
- D050000L
- DejaVu Sans
- DejaVu Sans Mono
- DejaVu Serif
- Dhurjati
- Dingbats
- Droid Sans Fallback
- Dyuthi
- Fira Code
- FontAwesome
- FreeMono
- FreeSans
- FreeSerif
- Gargi
- Garuda
- Gayathri
- Gidugu
- Gubbi
- Gurajada
- Iosevka
- Jamrul
- KacstArt
- KacstBook
- KacstDecorative
- KacstDigital
- KacstFarsi
- KacstLetter
- KacstNaskh
- KacstOffice
- KacstOne
- KacstPen
- KacstPoster
- KacstQurn
- KacstScreen
- KacstTitle
- KacstTitleL
- Kalapi
- Kalimati
- Karumbi
- Keraleeyam
- Khmer OS
- Khmer OS System
- Kinnari
- LKLUG
- LakkiReddy
- Laksaman
- Latin Modern Math
- Latin Modern Mono
- Latin Modern Mono Caps
- Latin Modern Mono Light
- Latin Modern Mono Light Cond
- Latin Modern Mono Prop
- Latin Modern Mono Prop Light
- Latin Modern Mono Slanted
- Latin Modern Roman
- Latin Modern Roman Caps
- Latin Modern Roman Demi
- Latin Modern Roman Dunhill
- Latin Modern Roman Slanted
- Latin Modern Roman Unslanted
- Latin Modern Sans
- Latin Modern Sans Demi Cond
- Latin Modern Sans Quotation
- Lato
- Liberation Mono
- Liberation Sans
- Liberation Sans Narrow
- Liberation Serif
- Likhan
- Lohit Assamese
- Lohit Bengali
- Lohit Devanagari
- Lohit Gujarati
- Lohit Gurmukhi
- Lohit Kannada
- Lohit Malayalam
- Lohit Odia
- Lohit Tamil
- Lohit Tamil Classical
- Lohit Telugu
- Loma
- Mallanna
- Mandali
- Manjari
- Material Icons
- Meera
- Mitra
- Mukti
- NATS
- NTR
- Nakula
- Navilu
- Nimbus Mono L
- Nimbus Mono PS
- Nimbus Roman
- Nimbus Roman No9 L
- Nimbus Sans
- Nimbus Sans L
- Nimbus Sans Narrow
- Norasi
- Noto Color Emoji
- Noto Mono
- Noto Sans CJK HK
- Noto Sans CJK JP
- Noto Sans CJK KR
- Noto Sans CJK SC
- Noto Sans CJK TC
- Noto Sans Mono
- Noto Sans Mono CJK HK
- Noto Sans Mono CJK JP
- Noto Sans Mono CJK KR
- Noto Sans Mono CJK SC
- Noto Sans Mono CJK TC
- Noto Serif CJK HK
- Noto Serif CJK JP
- Noto Serif CJK KR
- Noto Serif CJK SC
- Noto Serif CJK TC
- OpenSymbol
- P052
- Padauk
- Padauk Book
- Pagul
- Peddana
- Phetsarath OT
- Ponnala
- Pothana2000
- Potti Sreeramulu
- Purisa
- Rachana
- RaghuMalayalamSans
- Ramabhadra
- Ramaraja
- Rasa
- RaviPrakash
- Rekha
- Saab
- Sahadeva
- Samanata
- Samyak Devanagari
- Samyak Gujarati
- Samyak Malayalam
- Samyak Tamil
- Sarai
- Sawasdee
- Sree Krushnadevaraya
- Standard Symbols L
- Standard Symbols PS
- Suranna
- Suravaram
- Suruma
- Syamala Ramana
- Symbols Nerd Font Mono
- TeX Gyre Adventor
- TeX Gyre Bonum
- TeX Gyre Bonum Math
- TeX Gyre Chorus
- TeX Gyre Cursor
- TeX Gyre DejaVu Math
- TeX Gyre Heros
- TeX Gyre Heros Cn
- TeX Gyre Pagella
- TeX Gyre Pagella Math
- TeX Gyre Schola
- TeX Gyre Schola Math
- TeX Gyre Termes
- TeX Gyre Termes Math
- TenaliRamakrishna
- Tibetan Machine Uni
- Timmana
- Tlwg Mono
- Tlwg Typewriter
- Tlwg Typist
- Tlwg Typo
- URW Bookman
- URW Bookman L
- URW Chancery L
- URW Gothic
- URW Gothic L
- URW Palladio L
- Ubuntu
- Ubuntu Condensed
- Ubuntu Mono
- Umpush
- Uroob
- Utopia
- Vemana2000
- Waree
- Weather Icons
- Yrsa
- Z003
- aakar
- all-the-icons
- bitstream charter
- clean
- clearlyu
- clearlyu alternate glyphs
- clearlyu arabic
- clearlyu arabic extra
- clearlyu devanagari
- clearlyu devangari extra
- clearlyu ligature
- clearlyu pua
- courier 10 pitch
- fangsong ti
- file-icons
- fixed
- github-octicons
- gothic
- latin modern roman
- latin modern sans
- latin modern sansquotation
- latin modern typewriter
- latin modern typewriter variable width
- mincho
- mry_KacstQurn
- newspaper
- nil
- open look cursor
- open look glyph
- ori1Uni
- padmaa
- padmaa-Bold.1.1
- song ti
- texgyreadventor
- texgyrebonum
- texgyrechorus
- texgyrecursor
- texgyreheros
- texgyrepagella
- texgyreschola
- texgyretermes

** 日本語の範囲をNotoフォントに設定
#+begin_src elisp :tangle yes
  ;; 日本語の範囲をNotoフォントに設定
  (when (display-graphic-p)
    (set-fontset-font nil 'japanese-jisx0208 (font-spec :family "Noto Serif CJK JP"))
    ;; (set-fontset-font nil 'japanese-jisx0208 (font-spec :family "Noto Sans CJK JP"))
    )
  #+end_src

** 確認用テーブル
|----------------------------------+------------------------|
| this is a header 1               | this is a header2      |
|----------------------------------+------------------------|
| これはヘッダー位置ですよーん漢字 | 揃っているみたいですね |
| カタカナ                         | カタカナ崩れませんか   |
|----------------------------------+------------------------|

** Notoフォントのインストール
*** Windows
#+begin_src bash
  kenjiro@um560-win11 MINGW64 ~
  $ scoop bucket add nerd-fonts
  Checking repo... OK
  The nerd-fonts bucket was added successfully.

  kenjiro@um560-win11 MINGW64 ~
  $ scoop search noto
  Results from local buckets...

  Name                          Version  Source     Binaries
  ----                          -------  ------     --------
  Noto-CJK-Mega-OTC             20190603 nerd-fonts
  Noto-NF-Mono                  3.2.1    nerd-fonts
  Noto-NF-Propo                 3.2.1    nerd-fonts
  Noto-NF                       3.2.1    nerd-fonts
  Source-Han-Noto-CJK-Ultra-OTC 20190603 nerd-fonts


  kenjiro@um560-win11 MINGW64 ~
  $ scoop install Noto-CJK-Mega-OTC
  Updating Scoop...
  Updating Buckets...
  Scoop was updated successfully!
  Installing 'Noto-CJK-Mega-OTC' (20190603) [64bit] from 'nerd-fonts' bucket
  NotoCJK.ttc (272.5 MB) [======================================================================================] 100%
  Checking hash of NotoCJK.ttc ... ok.
  Running installer script...done.
  Linking ~\scoop\apps\Noto-CJK-Mega-OTC\current => ~\scoop\apps\Noto-CJK-Mega-OTC\20190603
  'Noto-CJK-Mega-OTC' (20190603) was installed successfully!

  kenjiro@um560-win11 MINGW64 ~
#+end_src

** Iosevkaフォントのインストール
https://github.com/be5invis/Iosevka
*** Linux
#+begin_src bash
  mkdir -p ~/Downloads
  cd ~/Downloads
  curl -O https://sid.ethz.ch/debian/fonts-iosevka/fonts-iosevka_22.0.0%2Bds-1_all.deb
  sudo dpkg -i fonts-iosevka_22.0.0%2Bds-1_all.deb
#+end_src

#+RESULTS:

*** Windows
#+begin_src bash
  kenjiro@um560-win11 MINGW64 ~
  $ scoop search iosevka
  Results from local buckets...

  Name                     Version Source     Binaries
  ----                     ------- ------     --------
  Iosevka-NF-Mono          3.2.1   nerd-fonts
  Iosevka-NF-Propo         3.2.1   nerd-fonts
  Iosevka-NF               3.2.1   nerd-fonts
  IosevkaTerm-NF-Mono      3.2.1   nerd-fonts
  IosevkaTerm-NF-Propo     3.2.1   nerd-fonts
  IosevkaTerm-NF           3.2.1   nerd-fonts
  IosevkaTermSlab-NF-Mono  3.2.1   nerd-fonts
  IosevkaTermSlab-NF-Propo 3.2.1   nerd-fonts
  IosevkaTermSlab-NF       3.2.1   nerd-fonts


  kenjiro@um560-win11 MINGW64 ~
  $ scoop install Iosevka-NF-Mono Iosevka-NF-Propo Iosevka-NF IosevkaTerm-NF-Mono IosevkaTerm-NF-Propo IosevkaTerm-NF IosevkaTermSlab-NF-Mono IosevkaTermSlab-NF-Propo IosevkaTermSlab-NF
  Installing 'Iosevka-NF-Mono' (3.2.1) [64bit] from 'nerd-fonts' bucket
  Iosevka.zip (324.0 MB) [======================================================================================] 100%
  Checking hash of Iosevka.zip ... ok.
  Extracting Iosevka.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\Iosevka-NF-Mono\current => ~\scoop\apps\Iosevka-NF-Mono\3.2.1
  'Iosevka-NF-Mono' (3.2.1) was installed successfully!
  Installing 'Iosevka-NF-Propo' (3.2.1) [64bit] from 'nerd-fonts' bucket
  Iosevka.zip (324.0 MB) [======================================================================================] 100%
  Checking hash of Iosevka.zip ... ok.
  Extracting Iosevka.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\Iosevka-NF-Propo\current => ~\scoop\apps\Iosevka-NF-Propo\3.2.1
  'Iosevka-NF-Propo' (3.2.1) was installed successfully!
  Installing 'Iosevka-NF' (3.2.1) [64bit] from 'nerd-fonts' bucket
  Iosevka.zip (324.0 MB) [======================================================================================] 100%
  Checking hash of Iosevka.zip ... ok.
  Extracting Iosevka.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\Iosevka-NF\current => ~\scoop\apps\Iosevka-NF\3.2.1
  'Iosevka-NF' (3.2.1) was installed successfully!
  Installing 'IosevkaTerm-NF-Mono' (3.2.1) [64bit] from 'nerd-fonts' bucket
  IosevkaTerm.zip (324.1 MB) [==================================================================================] 100%
  Checking hash of IosevkaTerm.zip ... ok.
  Extracting IosevkaTerm.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\IosevkaTerm-NF-Mono\current => ~\scoop\apps\IosevkaTerm-NF-Mono\3.2.1
  'IosevkaTerm-NF-Mono' (3.2.1) was installed successfully!
  Installing 'IosevkaTerm-NF-Propo' (3.2.1) [64bit] from 'nerd-fonts' bucket
  IosevkaTerm.zip (324.1 MB) [==================================================================================] 100%
  Checking hash of IosevkaTerm.zip ... ok.
  Extracting IosevkaTerm.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\IosevkaTerm-NF-Propo\current => ~\scoop\apps\IosevkaTerm-NF-Propo\3.2.1
  'IosevkaTerm-NF-Propo' (3.2.1) was installed successfully!
  Installing 'IosevkaTerm-NF' (3.2.1) [64bit] from 'nerd-fonts' bucket
  IosevkaTerm.zip (324.1 MB) [==================================================================================] 100%
  Checking hash of IosevkaTerm.zip ... ok.
  Extracting IosevkaTerm.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\IosevkaTerm-NF\current => ~\scoop\apps\IosevkaTerm-NF\3.2.1
  'IosevkaTerm-NF' (3.2.1) was installed successfully!
  Installing 'IosevkaTermSlab-NF-Mono' (3.2.1) [64bit] from 'nerd-fonts' bucket
  IosevkaTermSlab.zip (182.4 MB) [==============================================================================] 100%
  Checking hash of IosevkaTermSlab.zip ... ok.
  Extracting IosevkaTermSlab.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\IosevkaTermSlab-NF-Mono\current => ~\scoop\apps\IosevkaTermSlab-NF-Mono\3.2.1
  'IosevkaTermSlab-NF-Mono' (3.2.1) was installed successfully!
  Installing 'IosevkaTermSlab-NF-Propo' (3.2.1) [64bit] from 'nerd-fonts' bucket
  IosevkaTermSlab.zip (182.4 MB) [==============================================================================] 100%
  Checking hash of IosevkaTermSlab.zip ... ok.
  Extracting IosevkaTermSlab.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\IosevkaTermSlab-NF-Propo\current => ~\scoop\apps\IosevkaTermSlab-NF-Propo\3.2.1
  'IosevkaTermSlab-NF-Propo' (3.2.1) was installed successfully!
  Installing 'IosevkaTermSlab-NF' (3.2.1) [64bit] from 'nerd-fonts' bucket
  IosevkaTermSlab.zip (182.4 MB) [==============================================================================] 100%
  Checking hash of IosevkaTermSlab.zip ... ok.
  Extracting IosevkaTermSlab.zip ... done.
  Running installer script...done.
  Linking ~\scoop\apps\IosevkaTermSlab-NF\current => ~\scoop\apps\IosevkaTermSlab-NF\3.2.1
  'IosevkaTermSlab-NF' (3.2.1) was installed successfully!
#+end_src

* ewwのフォントが汚い件
#+begin_src
M-x eww-toggle-fonts
または
F => Shift-f
#+end_src

* Eglot導入
lspサーバーとの比較のため導入してみる
#+begin_src elisp :tangle yes
  (use-package eglot
    :ensure t
    :hook
    (c-mode . eglot-ensure)
    (c++-mode . eglot-ensure)
    (objc-mode . eglot-ensure)
    :config
    (add-to-list 'eglot-server-programs '((c-mode c++-mode objc-mode) "clangd")))
#+end_src
* Tree sitter
#+begin_src elisp :tangle yes
  ;; 構文解析エンジン Tree sitter
  (unless (version< emacs-version "29.0")
    (use-package treesit-auto
      :ensure t
      :config
      (setq treesit-auto-install t)
      (global-treesit-auto-mode)))
#+end_src
* フレームの回転
#+begin_src elisp :tangle yes
  ;; フレームの回転
  (use-package transpose-frame
    :ensure t)
#+end_src
* ウィンドウのリサイズ
#+begin_src elisp :tangle yes
  ;; C-s <araow keys> でウィンドウのサイズをマウスを使わずに調節する
  ;;
  ;; Window Resize
  ;; https://www.emacswiki.org/emacs/WindowResize
  ;;
  (defun win-resize-top-or-bot ()
    "Figure out if the current window is on top, bottom or in the
  middle"
    (let* ((win-edges (window-edges))
           (this-window-y-min (nth 1 win-edges))
           (this-window-y-max (nth 3 win-edges))
           (fr-height (frame-height)))
      (cond
       ((eq 0 this-window-y-min) "top")
       ((eq (- fr-height 1) this-window-y-max) "bot")
       (t "mid"))))

  (defun win-resize-left-or-right ()
    "Figure out if the current window is to the left, right or in the
  middle"
    (let* ((win-edges (window-edges))
           (this-window-x-min (nth 0 win-edges))
           (this-window-x-max (nth 2 win-edges))
           (fr-width (frame-width)))
      (cond
       ((eq 0 this-window-x-min) "left")
       ((eq (+ fr-width 4) this-window-x-max) "right")
       (t "mid"))))

  (defun win-resize-enlarge-horiz ()
    (interactive)
    (cond
     ((equal "top" (win-resize-top-or-bot)) (enlarge-window -1))
     ((equal "bot" (win-resize-top-or-bot)) (enlarge-window 1))
     ((equal "mid" (win-resize-top-or-bot)) (enlarge-window -1))
     (t (message "nil"))))

  (defun win-resize-minimize-horiz ()
    (interactive)
    (cond
     ((equal "top" (win-resize-top-or-bot)) (enlarge-window 1))
     ((equal "bot" (win-resize-top-or-bot)) (enlarge-window -1))
     ((equal "mid" (win-resize-top-or-bot)) (enlarge-window 1))
     (t (message "nil"))))

  (defun win-resize-enlarge-vert ()
    (interactive)
    (cond
     ((equal "left" (win-resize-left-or-right)) (enlarge-window-horizontally -1))
     ((equal "right" (win-resize-left-or-right)) (enlarge-window-horizontally 1))
     ((equal "mid" (win-resize-left-or-right)) (enlarge-window-horizontally -1))))

  (defun win-resize-minimize-vert ()
    (interactive)
    (cond
     ((equal "left" (win-resize-left-or-right)) (enlarge-window-horizontally 1))
     ((equal "right" (win-resize-left-or-right)) (enlarge-window-horizontally -1))
     ((equal "mid" (win-resize-left-or-right)) (enlarge-window-horizontally 1))))

  ;; replace all C-M-(down|up|left|right) to
  ;;             C-s-(down|up|left|right)
  ;; reason for confilict to paredit
  (global-set-key [C-s-down] 'win-resize-minimize-vert)
  (global-set-key [C-s-up] 'win-resize-enlarge-vert)
  (global-set-key [C-s-left] 'win-resize-minimize-horiz)
  (global-set-key [C-s-right] 'win-resize-enlarge-horiz)
  (global-set-key [C-s-up] 'win-resize-enlarge-horiz)
  (global-set-key [C-s-down] 'win-resize-minimize-horiz)
  (global-set-key [C-s-left] 'win-resize-enlarge-vert)
  (global-set-key [C-s-right] 'win-resize-minimize-vert)
#+end_src
* sudo編集
#+begin_src elisp :tangle yes
  (use-package sudo-edit
    :ensure t
    :pin melpa)
#+end_src
* Which Key
 [[https://github.com/justbur/emacs-which-key][which-key]] is a useful UI panel that appears when you start pressing any key binding in Emacs to offer you all possible completions for the prefix.  For example, if you press =C-c= (hold control and press the letter =c=), a panel will appear at the bottom of the frame displaying all of the bindings under that prefix and which command they run.  This is very useful for learning the possible key bindings in the mode of your current buffer.
#+begin_src emacs-lisp :tangle yes
  (use-package which-key
    :defer 0
    :diminish which-key-mode
    :config
    (which-key-mode)
    (setq which-key-idle-delay 1))
#+end_src
* アイコン装飾
#+begin_src elisp :tangle yes
  (use-package all-the-icons
    :if (display-graphic-p))

  (when (display-graphic-p)
    (use-package nerd-icons)
    (unless (kf:font-family-installed-p "all-the-icons")
      (all-the-icons-install-fonts))
    (unless (kf:font-family-installed-p "symbols nerd")
      (nerd-icons-install-fonts)))

  (use-package all-the-icons-dired
    :if (display-graphic-p)
    :hook (dired-mode . all-the-icons-dired-mode))
#+end_src
* astyle
#+begin_src elisp :tangle yes
  (use-package astyle
    :ensure t
    :when (executable-find "astyle"))
#+end_src
* CMake 対応
#+begin_src elisp :tangle yes
  (use-package cmake-mode
    :ensure t)
  (setq auto-mode-alist
        (append
         '(("CMakeLists\\.txt\\'" . cmake-mode))
         '(("\\.cmake\\'" . cmake-mode))
         auto-mode-alist))
#+end_src
* 末尾のゴミを可視化
#+begin_src elisp :tangle yes
  ;; https://qiita.com/tadsan/items/df73c711f921708facdc
  (setq-default show-trailing-whitespace t)
  (defun my/disable-trailing-mode-hook ()
    "Disable show tail whitespace."
    (setq show-trailing-whitespace nil))

  (defvar my/disable-trailing-modes
    '(comint-mode
      eshell-mode
      eww-mode
      term-mode
      vterm-mode
      twittering-mode))

  (mapc
   (lambda (mode)
     (add-hook (intern (concat (symbol-name mode) "-hook"))
               'my/disable-trailing-mode-hook))
   my/disable-trailing-modes)
#+end_src
* モードラインをシンプル化
#+begin_src elisp :tangle yes
  (use-package doom-modeline
    :if (and (display-graphic-p) (not (eq system-type 'haiku)))
    :init
    (doom-modeline-mode +1))
#+end_src
* Iosevkaを標準フォントに
#+begin_src elisp :tangle yes
  ;; TODO この対策は一時的なものであるため、通常のoptionsに戻すのを忘れないこと
  (when (and (display-graphic-p) (kf:font-family-installed-p "iosevka"))
    (let ((font-height (if (< (display-pixel-height) 900) 100 130))
          (custom-set-faces
           ;; custom-set-faces was added by Custom.
           ;; If you edit it by hand, you could mess it up, so be careful.
           ;; Your init file should contain only one such instance.
           ;; If there is more than one, they won't work right.
           ;;
           '(default ((t (:family "Iosevka" :foundry "UKWN" :slant normal :weight regular :height font-height :width normal))))
           ))))
#+end_src

* デスクトップのサイズを記憶
#+begin_src elisp :tangle yes
  ;; デスクトップ環境の保存
  ;; https://www.gnu.org/software/emacs//manual/html_node/emacs/Saving-Emacs-Sessions.html
  (desktop-save-mode (if (display-graphic-p) +1 -1))
  ;; ホスト名を付加してファイル名衝突回避
  (setq desktop-base-file-name (concat "." (safe-host-name-string) "-emacs.desktop"))
#+end_src

#+begin_src elisp :results output
  desktop-path
  desktop-base-file-name
  (safe-host-name-string)
#+end_src

#+RESULTS:
#+begin_src elisp :tangle yes
  (use-package ef-themes
    :ensure t
    :config
    (ef-themes-select 'ef-cyprus))
#+end_src

* グローバル高速検索
#+begin_src elisp :tangle yes
  ;; https://agel.readthedocs.io/en/latest/index.html
  (use-package ag
    :ensure t)
#+end_src

* TODO 垂直分割より水分平割を優先する(表現が逆かな)
一時的にオフにしておく、frame が縦長か横長かの判定で切り分ける
frame-geometry関数のouter-sizeで判定すること
#+begin_src elisp :tangle no
  ;; https://qiita.com/nobuyuki86/items/6b7aa2f17faa63b6a900#%E6%B0%B4%E5%B9%B3%E5%88%86%E5%89%B2%E3%82%88%E3%82%8A%E5%9E%82%E7%9B%B4%E5%88%86%E5%89%B2%E3%82%92%E5%84%AA%E5%85%88%E3%81%99%E3%82%8B
  (setq split-height-threshold nil)
  (setq split-width-threshold 0)
#+end_src
* TODO 導入予定
** TODO narrow時にツリー間の移動を用意にし、プレゼンテーションも行える
https://protesilaos.com/emacs/logos
** TODO モードラインに IME 情報が載せられないか?

* Projectile
#+begin_src elisp :tangle yes
  (use-package projectile
    :config
    (defun projectile-project-find-function (dir)
      (let* ((root (projectile-project-root dir)))
        (and root (cons 'transient root))))
    (with-eval-after-load 'project
      (add-to-list 'project-find-functions 'projectile-project-find-function))
    )

  ;; (use-package eglot
  ;;   :bind (:map eglot-mode-map
  ;;               ("C-c C-d" . eglot-help-at-point)
  ;;               ("C-c C-r" . eglot-code-actions))
  ;;   :hook
  ;;   ((c-mode-common . eglot-ensure))
  ;;   )
#+end_src

* ObjC
#+begin_src elisp :tangle yes
  (defun kf:c-mode-init ()
    (c-toggle-auto-newline 1)
    (setq c-hanging-braces-alist '((statement-open before after)
                                   (substatement-open before after) ))
    )
  (defun kf:objc-mode-init ()
    (c-toggle-auto-newline 1)
    (setq c-hanging-braces-alist '((statement before after)
                                   (statement-open before after)
                                   (substatement-open before after) ))
    )
  (add-hook 'c-mode-hook 'kf:c-mode-init)
  (add-hook 'objc-mode-hook 'kf:objc-mode-init)

  ;; https://qiita.com/fujimisakari/items/a6ff082f0e8eddc09511
  ;; .hファイルもobjc-modeで開くけるようにする
  (add-to-list 'magic-mode-alist
               `(,(lambda ()
                    (and (string= (file-name-extension buffer-file-name) "h")
                         (re-search-forward "@\\<interface\\>"
                                            magic-mode-regexp-match-limit t)))
                 . objc-mode))
#+end_src

#+RESULTS:
| kf:objc-mode-init | er/add-cc-mode-expansions | eglot-ensure |

* ClangFormat
#+begin_src elisp :tangle yes
(use-package clang-format
  :ensure t)
#+end_src

#+RESULTS:
* GNUstep Renaissance
#+begin_src elisp :tangle yes
 (add-to-list 'auto-mode-alist '("\\.gsmarkup$" . xml-mode))
#+end_src

#+RESULTS:
: ((\.gsmarkup$ . xml-mode) (\.css\' . css-ts-mode) (\(?:\.\(?:rbw?\|ru\|rake\|thor\|jbuilder\|rabl\|gemspec\|podspec\)\|/\(?:Gem\|Rake\|Cap\|Thor\|Puppet\|Berks\|Brew\|Vagrant\|Guard\|Pod\)file\)\' . ruby-ts-mode) (\.java\' . java-ts-mode) (\.x[pb]m\' . image-mode) (\.x[pb]m\' . c-ts-mode) (\(\.[chi]\|\.lex\|\.y\(acc\)?\)\' . c-ts-mode) (CMakeLists\.txt\' . cmake-mode) (\.cmake\' . cmake-mode) (\.md\' . markdown-mode) (\.cmake\' . cmake-mode) (CMakeLists\.txt\' . cmake-mode) (\.editorconfig\' . editorconfig-conf-mode) (/git-rebase-todo\' . git-rebase-mode) (\.\(?:md\|markdown\|mkd\|mdown\|mkdn\|mdwn\)\' . markdown-mode) (\.gpg\(~\|\.~[0-9]+~\)?\' nil epa-file) (\.elc\' . elisp-byte-code-mode) (\.zst\' nil jka-compr) (\.dz\' nil jka-compr) (\.xz\' nil jka-compr) (\.lzma\' nil jka-compr) (\.lz\' nil jka-compr) (\.g?z\' nil jka-compr) (\.bz2\' nil jka-compr) (\.Z\' nil jka-compr) (\.vr[hi]?\' . vera-mode) (\(?:\.\(?:rbw?\|ru\|rake\|thor\|jbuilder\|rabl\|gemspec\|podspec\)\|/\(?:Gem\|Rake\|Cap\|Thor\|Puppet\|Berks\|Brew\|Vagrant\|Guard\|Pod\)file\)\' . ruby-mode) (\.re?st\' . rst-mode) (\.py[iw]?\' . python-mode) (\.m\' . octave-maybe-mode) (\.less\' . less-css-mode) (\.scss\' . scss-mode) (\.cs\' . csharp-mode) (\.awk\' . awk-mode) (\.\(u?lpc\|pike\|pmod\(\.in\)?\)\' . pike-mode) (\.idl\' . idl-mode) (\.java\' . java-mode) (\.m\' . objc-mode) (\.ii\' . c++-mode) (\.i\' . c-mode) (\.lex\' . c-mode) (\.y\(acc\)?\' . c-mode) (\.h\' . c-or-c++-mode) (\.c\' . c-mode) (\.\(CC?\|HH?\)\' . c++-mode) (\.[ch]\(pp\|xx\|\+\+\)\' . c++-mode) (\.\(cc\|hh\)\' . c++-mode) (\.\(bat\|cmd\)\' . bat-mode) (\.[sx]?html?\(\.[a-zA-Z_]+\)?\' . mhtml-mode) (\.svgz?\' . image-mode) (\.svgz?\' . xml-mode) (\.x[bp]m\' . image-mode) (\.x[bp]m\' . c-mode) (\.p[bpgn]m\' . image-mode) (\.tiff?\' . image-mode) (\.gif\' . image-mode) (\.png\' . image-mode) (\.jpe?g\' . image-mode) (\.webp\' . image-mode) (\.te?xt\' . text-mode) (\.[tT]e[xX]\' . tex-mode) (\.ins\' . tex-mode) (\.ltx\' . latex-mode) (\.dtx\' . doctex-mode) (\.org\' . org-mode) (\.dir-locals\(?:-2\)?\.el\' . lisp-data-mode) (\.eld\' . lisp-data-mode) (eww-bookmarks\' . lisp-data-mode) (tramp\' . lisp-data-mode) (/archive-contents\' . lisp-data-mode) (places\' . lisp-data-mode) (\.emacs-places\' . lisp-data-mode) (\.el\' . emacs-lisp-mode) (Project\.ede\' . emacs-lisp-mode) (\.\(scm\|sls\|sld\|stk\|ss\|sch\)\' . scheme-mode) (\.l\' . lisp-mode) (\.li?sp\' . lisp-mode) (\.[fF]\' . fortran-mode) (\.for\' . fortran-mode) (\.p\' . pascal-mode) (\.pas\' . pascal-mode) (\.\(dpr\|DPR\)\' . delphi-mode) (\.\([pP]\([Llm]\|erl\|od\)\|al\)\' . perl-mode) (Imakefile\' . makefile-imake-mode) (Makeppfile\(?:\.mk\)?\' . makefile-makepp-mode) (\.makepp\' . makefile-makepp-mode) (\.mk\' . makefile-gmake-mode) (\.make\' . makefile-gmake-mode) ([Mm]akefile\' . makefile-gmake-mode) (\.am\' . makefile-automake-mode) (\.texinfo\' . texinfo-mode) (\.te?xi\' . texinfo-mode) (\.[sS]\' . asm-mode) (\.asm\' . asm-mode) (\.css\' . css-mode) (\.mixal\' . mixal-mode) (\.gcov\' . compilation-mode) (/\.[a-z0-9-]*gdbinit . gdb-script-mode) (-gdb\.gdb . gdb-script-mode) ([cC]hange\.?[lL]og?\' . change-log-mode) ([cC]hange[lL]og[-.][0-9]+\' . change-log-mode) (\$CHANGE_LOG\$\.TXT . change-log-mode) (\.scm\.[0-9]*\' . scheme-mode) (\.[ckz]?sh\'\|\.shar\'\|/\.z?profile\' . sh-mode) (\.bash\' . sh-mode) (/PKGBUILD\' . sh-mode) (\(/\|\`\)\.\(bash_\(profile\|history\|log\(in\|out\)\)\|z?log\(in\|out\)\)\' . sh-mode) (\(/\|\`\)\.\(shrc\|zshrc\|m?kshrc\|bashrc\|t?cshrc\|esrc\)\' . sh-mode) (\(/\|\`\)\.\([kz]shenv\|xinitrc\|startxrc\|xsession\)\' . sh-mode) (\.m?spec\' . sh-mode) (\.m[mes]\' . nroff-mode) (\.man\' . nroff-mode) (\.sty\' . latex-mode) (\.cl[so]\' . latex-mode) (\.bbl\' . latex-mode) (\.bib\' . bibtex-mode) (\.bst\' . bibtex-style-mode) (\.sql\' . sql-mode) (\(acinclude\|aclocal\|acsite\)\.m4\' . autoconf-mode) (\.m[4c]\' . m4-mode) (\.mf\' . metafont-mode) (\.mp\' . metapost-mode) (\.vhdl?\' . vhdl-mode) (\.article\' . text-mode) (\.letter\' . text-mode) (\.i?tcl\' . tcl-mode) (\.exp\' . tcl-mode) (\.itk\' . tcl-mode) (\.icn\' . icon-mode) (\.sim\' . simula-mode) (\.mss\' . scribe-mode) (\.f9[05]\' . f90-mode) (\.f0[38]\' . f90-mode) (\.indent\.pro\' . fundamental-mode) (\.\(pro\|PRO\)\' . idlwave-mode) (\.srt\' . srecode-template-mode) (\.prolog\' . prolog-mode) (\.tar\' . tar-mode) (\.\(arc\|zip\|lzh\|lha\|zoo\|[jew]ar\|xpi\|rar\|cbr\|7z\|squashfs\|ARC\|ZIP\|LZH\|LHA\|ZOO\|[JEW]AR\|XPI\|RAR\|CBR\|7Z\|SQUASHFS\)\' . archive-mode) (\.oxt\' . archive-mode) (\.\(deb\|[oi]pk\)\' . archive-mode) (\`/tmp/Re . text-mode) (/Message[0-9]*\' . text-mode) (\`/tmp/fol/ . text-mode) (\.oak\' . scheme-mode) (\.sgml?\' . sgml-mode) (\.x[ms]l\' . xml-mode) (\.dbk\' . xml-mode) (\.dtd\' . sgml-mode) (\.ds\(ss\)?l\' . dsssl-mode) (\.js[mx]?\' . javascript-mode) (\.har\' . javascript-mode) (\.json\' . js-json-mode) (\.[ds]?va?h?\' . verilog-mode) (\.by\' . bovine-grammar-mode) (\.wy\' . wisent-grammar-mode) (\.erts\' . erts-mode) ([:/\]\..*\(emacs\|gnus\|viper\)\' . emacs-lisp-mode) (\`\..*emacs\' . emacs-lisp-mode) ([:/]_emacs\' . emacs-lisp-mode) (/crontab\.X*[0-9]+\' . shell-script-mode) (\.ml\' . lisp-mode) (\.ld[si]?\' . ld-script-mode) (ld\.?script\' . ld-script-mode) (\.xs\' . c-mode) (\.x[abdsru]?[cnw]?\' . ld-script-mode) (\.zone\' . dns-mode) (\.soa\' . dns-mode) (\.asd\' . lisp-mode) (\.\(asn\|mib\|smi\)\' . snmp-mode) (\.\(as\|mi\|sm\)2\' . snmpv2-mode) (\.\(diffs?\|patch\|rej\)\' . diff-mode) (\.\(dif\|pat\)\' . diff-mode) (\.[eE]?[pP][sS]\' . ps-mode) (\.\(?:PDF\|EPUB\|CBZ\|FB2\|O?XPS\|DVI\|OD[FGPST]\|DOCX\|XLSX?\|PPTX?\|pdf\|epub\|cbz\|fb2\|o?xps\|djvu\|dvi\|od[fgpst]\|docx\|xlsx?\|pptx?\)\' . doc-view-mode-maybe) (configure\.\(ac\|in\)\' . autoconf-mode) (\.s\(v\|iv\|ieve\)\' . sieve-mode) (BROWSE\' . ebrowse-tree-mode) (\.ebrowse\' . ebrowse-tree-mode) (#\*mail\* . mail-mode) (\.g\' . antlr-mode) (\.mod\' . m2-mode) (\.ses\' . ses-mode) (\.docbook\' . sgml-mode) (\.com\' . dcl-mode) (/config\.\(?:bat\|log\)\' . fundamental-mode) (/\.\(authinfo\|netrc\)\' . authinfo-mode) (\.\(?:[iI][nN][iI]\|[lL][sS][tT]\|[rR][eE][gG]\|[sS][yY][sS]\)\' . conf-mode) (\.la\' . conf-unix-mode) (\.ppd\' . conf-ppd-mode) (java.+\.conf\' . conf-javaprop-mode) (\.properties\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-javaprop-mode) (\.toml\' . conf-toml-mode) (\.desktop\' . conf-desktop-mode) (/\.redshift\.conf\' . conf-windows-mode) (\`/etc/\(?:DIR_COLORS\|ethers\|.?fstab\|.*hosts\|lesskey\|login\.?de\(?:fs\|vperm\)\|magic\|mtab\|pam\.d/.*\|permissions\(?:\.d/.+\)?\|protocols\|rpc\|services\)\' . conf-space-mode) (\`/etc/\(?:acpid?/.+\|aliases\(?:\.d/.+\)?\|default/.+\|group-?\|hosts\..+\|inittab\|ksysguarddrc\|opera6rc\|passwd-?\|shadow-?\|sysconfig/.+\)\' . conf-mode) ([cC]hange[lL]og[-.][-0-9a-z]+\' . change-log-mode) (/\.?\(?:gitconfig\|gnokiirc\|hgrc\|kde.*rc\|mime\.types\|wgetrc\)\' . conf-mode) (/\.mailmap\' . conf-unix-mode) (/\.\(?:asound\|enigma\|fetchmail\|gltron\|gtk\|hxplayer\|mairix\|mbsync\|msmtp\|net\|neverball\|nvidia-settings-\|offlineimap\|qt/.+\|realplayer\|reportbug\|rtorrent\.\|screen\|scummvm\|sversion\|sylpheed/.+\|xmp\)rc\' . conf-mode) (/\.\(?:gdbtkinit\|grip\|mpdconf\|notmuch-config\|orbital/.+txt\|rhosts\|tuxracer/options\)\' . conf-mode) (/\.?X\(?:default\|resource\|re\)s\> . conf-xdefaults-mode) (/X11.+app-defaults/\|\.ad\' . conf-xdefaults-mode) (/X11.+locale/.+/Compose\' . conf-colon-mode) (/X11.+locale/compose\.dir\' . conf-javaprop-mode) (\.~?[0-9]+\.[0-9][-.0-9]*~?\' nil t) (\.\(?:orig\|in\|[bB][aA][kK]\)\' nil t) ([/.]c\(?:on\)?f\(?:i?g\)?\(?:\.[a-zA-Z0-9._-]+\)?\' . conf-mode-maybe) (\.[1-9]\' . nroff-mode) (\.art\' . image-mode) (\.avs\' . image-mode) (\.bmp\' . image-mode) (\.cmyk\' . image-mode) (\.cmyka\' . image-mode) (\.crw\' . image-mode) (\.dcr\' . image-mode) (\.dcx\' . image-mode) (\.dng\' . image-mode) (\.dpx\' . image-mode) (\.fax\' . image-mode) (\.heic\' . image-mode) (\.hrz\' . image-mode) (\.icb\' . image-mode) (\.icc\' . image-mode) (\.icm\' . image-mode) (\.ico\' . image-mode) (\.icon\' . image-mode) (\.jbg\' . image-mode) (\.jbig\' . image-mode) (\.jng\' . image-mode) (\.jnx\' . image-mode) (\.miff\' . image-mode) (\.mng\' . image-mode) (\.mvg\' . image-mode) (\.otb\' . image-mode) (\.p7\' . image-mode) (\.pcx\' . image-mode) (\.pdb\' . image-mode) (\.pfa\' . image-mode) (\.pfb\' . image-mode) (\.picon\' . image-mode) (\.pict\' . image-mode) (\.rgb\' . image-mode) (\.rgba\' . image-mode) (\.tga\' . image-mode) (\.wbmp\' . image-mode) (\.webp\' . image-mode) (\.wmf\' . image-mode) (\.wpg\' . image-mode) (\.xcf\' . image-mode) (\.xmp\' . image-mode) (\.xwd\' . image-mode) (\.yuv\' . image-mode) (\.tgz\' . tar-mode) (\.tbz2?\' . tar-mode) (\.txz\' . tar-mode) (\.tzst\' . tar-mode))

* NeoTree
#+begin_src elisp :tangle yes
  ;; NeoTree
  ;; https://tsuu32.hatenablog.com/entry/2020/08/19/004306
  (use-package neotree
    :ensure t
    :config
    (setq neo-show-hidden-files t) ; dot-fileも表示する
    (setq neo-theme 'icons) )
#+end_src
* Orderless
#+begin_src elisp :tangle yes
  (use-package orderless
    :ensure t
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src
* Mozc
#+begin_src elisp :tangle no
  ;; sudo apt install -y emacs-mozc emacs-mozc-bin
  ;; 現在、 cl deprecated で起動エラーが出るため、OFFにしておく
  (when (kf:ensure-load-file "/usr/share/emacs/site-lisp/emacs-mozc/mozc.el")
    (setq default-input-method "japanese-mozc"))

      #+end_src

#+RESULTS:

ジャパニーズもずく打てますかね？
入力の感触は良いが、インライン変換できるのは気持ちが良い。

* Haiku Support
** Setup Jamfile mode
#+begin_src elisp :tangle yes
  ;; Haiku build system
  (kf:ensure-load-file "~/.emacs.d/lisp/jam-mode.el")

#+end_src

** Haiku Format
* マルチプルカーソル
- [[https://emacsrocks.com/e13.html]]
- [[https://github.com/magnars/multiple-cursors.el]]
#+begin_src elisp :tangle yes
  (use-package multiple-cursors
    :ensure t)

  (global-set-key (kbd "C-S-c C-S-c") 'mc/edit-lines)
  (global-set-key (kbd "C->")         'mc/mark-next-like-this)
  (global-set-key (kbd "C-<")         'mc/mark-previous-like-this)
  (global-set-key (kbd "C-c C-<")     'mc/mark-all-like-this)
  (global-set-key (kbd "C-\"")        'mc/skip-to-next-like-this)
  (global-set-key (kbd "C-:")         'mc/skip-to-previous-like-this)
#+end_src

#+RESULTS:
* Transclude
#+begin_src elisp :tangle yes
  (use-package org-transclusion
    :ensure t
    :after org)
  (define-key global-map (kbd "C-c <f12>") #'org-transclusion-add)
  (define-key global-map (kbd "C-c t") #'org-transclusion-mode)
#+end_src
* 定型文の挿入
#+begin_src elisp :tangle yes
  (use-package yasnippet)
  (use-package yasnippet-snippets)
#+end_src
* Common Lisp環境
#+begin_src elisp :tangle yes
  ;; https://github.com/roswell/roswell
  (kf:ensure-load-file "~/.roswell/helper.el")

#+end_src
* Free Basic
#+begin_src elisp :tangle yes
  ;; https://github.com/rversteegen/fb-mode
  (kf:ensure-load-file "~/.emacs.d/lisp/fb-mode.el")

#+end_src


* 末尾
#+BEGIN_SRC elisp :tangle yes
  (recentf-open-files)
#+END_SRC
